#!/usr/bin/env python3
# coding: utf-8

import os
from sqlalchemy import create_engine, MetaData
from sqlalchemy.orm import sessionmaker

from data_management.websites import LeMonde, Liberation, LeFigaro, LePoint, LeParisien
import data_management.model as model

# echo == debug mode
dir_path = os.path.dirname(os.path.realpath(__file__))
engine = create_engine('sqlite:///' + dir_path + '/../account.db')
Session = sessionmaker(bind=engine)
model.Base.metadata.drop_all(engine)
model.Base.metadata.create_all(engine)

if __name__ == '__main__':
    session = Session()
    try:
        LeMonde(session).load_une(session)
        # Liberation(session).load_une(session)
        # LeFigaro(session).load_une(session)
        # LePoint(session).load_une(session)
        # LeParisien(session).load_une(session)
    except:
        session.rollback()
        raise
    finally:
        session.close()
