#!/usr/bin/env python3
# coding: utf-8

import os
from sqlalchemy import create_engine, MetaData
from sqlalchemy.orm import sessionmaker

from data_management.lemonde import LeMonde
import data_management.model as model

# echo == debug mode
dir_path = os.path.dirname(os.path.realpath(__file__))
engine = create_engine('sqlite:///' + dir_path + '/../account.db', echo=True)
Session = sessionmaker(bind=engine)
model.Base.metadata.drop_all(engine)
model.Base.metadata.create_all(engine)

if __name__ == '__main__':
    session = Session()
    try:
        lemonde = LeMonde(session)
        lemonde.load_une(session)
        print(session.query(model.Article).all())
    except:
        session.rollback()
        raise
    finally:
        session.close()
