#!/usr/bin/env python3
# coding: utf-8

from sqlalchemy import create_engine, MetaData
from sqlalchemy.orm import sessionmaker

from lemonde import LeMonde
import model

# echo == debug mode
engine = create_engine('sqlite:///../account.db', echo=True)
Session = sessionmaker(bind=engine)
model.Base.metadata.drop_all(engine)
model.Base.metadata.create_all(engine)

if __name__ == '__main__':
    session = Session()
    try:
        lemonde = LeMonde(session)
        lemonde.load_une(session)
        print(lemonde.get_une(session))
    except:
        session.rollback()
        raise
    finally:
        session.close()
